// <auto-generated />
using System;
using Med.Data.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Med.Data.Ef.Migrations
{
    [DbContext(typeof(MedDbContext))]
    [Migration("20260820195244_Pocetna")]
    partial class Pocetna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Med.Domain.Entities.Adresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(60)")
                        .HasDefaultValue("Hrvatska")
                        .HasColumnName("drzava");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("grad");

                    b.Property<string>("KucniBroj")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("kucni_broj");

                    b.Property<string>("PostanskiBroj")
                        .HasColumnType("char(5)")
                        .HasColumnName("postanski_broj");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("ulica");

                    b.HasKey("Id");

                    b.ToTable("adrese", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Dijagnoza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sifra");

                    b.HasKey("Id");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("dijagnoze", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.KartonPacijenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergije")
                        .HasColumnType("text")
                        .HasColumnName("alergije");

                    b.Property<string>("KrvnaGrupa")
                        .HasColumnType("char(3)")
                        .HasColumnName("krvna_grupa");

                    b.Property<int>("PacijentId")
                        .HasColumnType("integer")
                        .HasColumnName("pacijent_id");

                    b.Property<double?>("TezinaKg")
                        .HasColumnType("double precision")
                        .HasColumnName("tezina_kg");

                    b.Property<double?>("VisinaCm")
                        .HasColumnType("double precision")
                        .HasColumnName("visina_cm");

                    b.HasKey("Id");

                    b.HasIndex("PacijentId")
                        .IsUnique();

                    b.ToTable("kartoni_pacijenata", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Lijecnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ime");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("prezime");

                    b.Property<string>("Specijalizacija")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specijalizacija");

                    b.HasKey("Id");

                    b.ToTable("lijecnici", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Lijek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtcKod")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("atc_kod");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("naziv");

                    b.Property<string>("Oblik")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("oblik");

                    b.HasKey("Id");

                    b.ToTable("lijekovi", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Pacijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresaBoravistaId")
                        .HasColumnType("integer")
                        .HasColumnName("adresa_boravista_id");

                    b.Property<int?>("AdresaPrebivalistaId")
                        .HasColumnType("integer")
                        .HasColumnName("adresa_prebivalista_id");

                    b.Property<DateTime>("DatumRodenja")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_rodenja");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ime");

                    b.Property<DateTimeOffset>("KreiranoNa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kreirano_na")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("oib");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("prezime");

                    b.Property<char>("Spol")
                        .HasColumnType("char(1)")
                        .HasColumnName("spol");

                    b.HasKey("Id");

                    b.HasIndex("AdresaBoravistaId");

                    b.HasIndex("AdresaPrebivalistaId");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.ToTable("pacijenti", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.PovijestBolesti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_do");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_od");

                    b.Property<int>("DijagnozaId")
                        .HasColumnType("integer")
                        .HasColumnName("dijagnoza_id");

                    b.Property<int>("LijecnikId")
                        .HasColumnType("integer")
                        .HasColumnName("lijecnik_id");

                    b.Property<string>("Napomena")
                        .HasColumnType("text")
                        .HasColumnName("napomena");

                    b.Property<int>("PacijentId")
                        .HasColumnType("integer")
                        .HasColumnName("pacijent_id");

                    b.HasKey("Id");

                    b.HasIndex("DijagnozaId");

                    b.HasIndex("LijecnikId");

                    b.HasIndex("PacijentId");

                    b.ToTable("povijest_bolesti", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Pregled", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LijecnikId")
                        .HasColumnType("integer")
                        .HasColumnName("lijecnik_id");

                    b.Property<string>("Nalaz")
                        .HasColumnType("text")
                        .HasColumnName("nalaz");

                    b.Property<int>("PacijentId")
                        .HasColumnType("integer")
                        .HasColumnName("pacijent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Zakazan'");

                    b.Property<DateTimeOffset>("Termin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termin");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tip");

                    b.Property<int>("TrajanjeMinuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("trajanje_minuta");

                    b.Property<int?>("UputiteljId")
                        .HasColumnType("integer")
                        .HasColumnName("uputitelj_id");

                    b.HasKey("Id");

                    b.HasIndex("LijecnikId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("UputiteljId");

                    b.ToTable("pregledi", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.Terapija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktivna");

                    b.Property<DateTime?>("DatumDo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_do");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datum_od");

                    b.Property<decimal>("Doza")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("doza");

                    b.Property<string>("JedinicaDoze")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("jedinica_doze");

                    b.Property<int>("LijecnikId")
                        .HasColumnType("integer")
                        .HasColumnName("lijecnik_id");

                    b.Property<int>("LijekId")
                        .HasColumnType("integer")
                        .HasColumnName("lijek_id");

                    b.Property<int>("PacijentId")
                        .HasColumnType("integer")
                        .HasColumnName("pacijent_id");

                    b.Property<int?>("PovijestBolestiId")
                        .HasColumnType("integer")
                        .HasColumnName("povijest_bolesti_id");

                    b.Property<string>("Ucestalost")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ucestalost");

                    b.HasKey("Id");

                    b.HasIndex("LijecnikId");

                    b.HasIndex("LijekId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("PovijestBolestiId");

                    b.ToTable("terapije", (string)null);
                });

            modelBuilder.Entity("Med.Domain.Entities.KartonPacijenta", b =>
                {
                    b.HasOne("Med.Domain.Entities.Pacijent", "Pacijent")
                        .WithOne("Karton")
                        .HasForeignKey("Med.Domain.Entities.KartonPacijenta", "PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("Med.Domain.Entities.Pacijent", b =>
                {
                    b.HasOne("Med.Domain.Entities.Adresa", "AdresaBoravista")
                        .WithMany()
                        .HasForeignKey("AdresaBoravistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Adresa", "AdresaPrebivalista")
                        .WithMany()
                        .HasForeignKey("AdresaPrebivalistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdresaBoravista");

                    b.Navigation("AdresaPrebivalista");
                });

            modelBuilder.Entity("Med.Domain.Entities.PovijestBolesti", b =>
                {
                    b.HasOne("Med.Domain.Entities.Dijagnoza", "Dijagnoza")
                        .WithMany()
                        .HasForeignKey("DijagnozaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Lijecnik", "Lijecnik")
                        .WithMany()
                        .HasForeignKey("LijecnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Pacijent", "Pacijent")
                        .WithMany("PovijestBolesti")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dijagnoza");

                    b.Navigation("Lijecnik");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("Med.Domain.Entities.Pregled", b =>
                {
                    b.HasOne("Med.Domain.Entities.Lijecnik", "Lijecnik")
                        .WithMany("Pregledi")
                        .HasForeignKey("LijecnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Pacijent", "Pacijent")
                        .WithMany("Pregledi")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Lijecnik", "Uputitelj")
                        .WithMany()
                        .HasForeignKey("UputiteljId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lijecnik");

                    b.Navigation("Pacijent");

                    b.Navigation("Uputitelj");
                });

            modelBuilder.Entity("Med.Domain.Entities.Terapija", b =>
                {
                    b.HasOne("Med.Domain.Entities.Lijecnik", "Lijecnik")
                        .WithMany()
                        .HasForeignKey("LijecnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Lijek", "Lijek")
                        .WithMany()
                        .HasForeignKey("LijekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.Pacijent", "Pacijent")
                        .WithMany("Terapije")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Med.Domain.Entities.PovijestBolesti", "PovijestBolesti")
                        .WithMany("Terapije")
                        .HasForeignKey("PovijestBolestiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lijecnik");

                    b.Navigation("Lijek");

                    b.Navigation("Pacijent");

                    b.Navigation("PovijestBolesti");
                });

            modelBuilder.Entity("Med.Domain.Entities.Lijecnik", b =>
                {
                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("Med.Domain.Entities.Pacijent", b =>
                {
                    b.Navigation("Karton");

                    b.Navigation("PovijestBolesti");

                    b.Navigation("Pregledi");

                    b.Navigation("Terapije");
                });

            modelBuilder.Entity("Med.Domain.Entities.PovijestBolesti", b =>
                {
                    b.Navigation("Terapije");
                });
#pragma warning restore 612, 618
        }
    }
}
