configfile: "config.yaml"

IZLAZ = config["izlaz"]


rule sve:
    input:
        f"{IZLAZ}/taksonomija.json",
        f"{IZLAZ}/datoteke.json",
        f"{IZLAZ}/klasifikacija.json",


rule taksonomija:
    output:
        f"{IZLAZ}/taksonomija.json",
    script:
        "skripte/taksonomija.py"


rule datoteke:
    output:
        f"{IZLAZ}/datoteke.json",
    script:
        "skripte/datoteke.py"


rule klasifikacija:
    input:
        f"{IZLAZ}/taksonomija.json",
        f"{IZLAZ}/datoteke.json",
    output:
        f"{IZLAZ}/klasifikacija.json",
    script:
        "skripte/klasifikacija.py"
